---
- name: Crear Reporte HTML
  become: true
  template:
    src: report.j2
    dest: "{{ file_path }}"

- name: DISPLAY LINK TO INVENTORY REPORT
  debug:
    msg: "Please go to http://{{ ansible_host }}/report"
