---
- name: Aplicar actualizaciones non-kernel
  hosts: "{{ HOSTS | default('all') }}"
  become: true
  gather_facts: false

  tasks:
    - name: Add the user {{user_name}} appending the group '{{user_groups}}' to the user's groups
      ansible.builtin.user:
        name: "{{user_name}}"
        groups: "{{user_groups}}"
        append: yes