---
- name: Aplicar actualizaciones non-kernel
  hosts: "{{ HOSTS | default('all') }}"
  become: true
  gather_facts: false

  tasks:
    - name: Add the user {{user_name}}
      ansible.builtin.user:
        name: "{{user_name}}"