---
- name: Actualizar todos los paquetes excepto el kernel
  yum:
    name: '*'
    state: latest
    exclude: kernel*
  tags: all

- name: Actualizar todos los paquetes de seguridad excepto el kernel
  yum:
    name: '*'
    state: latest
    security: true
    exclude: kernel*
  tags: security