---
- name: Creacion de usuarios en OS RHEL
  hosts: "{{ HOSTS | default('all') }}"
  become: true
  gather_facts: false

  tasks:
    - name: Agregar el usuario {{user_name}}
      ansible.builtin.user:
        name: "{{user_name}}"
        password: "{{user_password | password_hash('sha512')}}"
        comment: "{{user_first_name}} {{user_last_name}}"