---
- name: Obtener Linux Facts
  hosts: all
  gather_facts: true

- name: Construir reporte de los hosts
  hosts: node1
  gather_facts: false

  vars:
    file_path: /var/www/html/report/index.html

  tasks:
    - name: use developer report
      include_role:
        name: "../roles/developer_report"
