---
- name: grant sudo
  hosts: "{{ HOSTS | default('all') }}"
  become: true
  gather_facts: false

  tasks:
    - name: Check if sudo user exists on system
      getent:
        database: passwd
        key: "{{ user_name }}"

    - name: create sudo rule
      copy:
        dest: "/etc/sudoers.d/{{ user_name }}"
        owner: root
        group: root
        mode: 0640
        content: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"