---
- name: Aplicar actualizaciones non-kernel
  hosts: "{{ HOSTS | default('all') }}"
  become: true
  gather_facts: false

  tasks:
    - name: Actualizar todos los paquetes incluyendo el kernel
      yum:
        name: '*'
        state: latest
      tags: complete

    - name: Actualizar todos los paquetes de seguridad excepto el kernel
      yum:
        name: '*'
        state: latest
        security: true
        exclude: kernel*
      tags: security